project:
  type: website
  output-dir: docs
  
website:
  title: "Erica Sherman's ePortfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: portfolio-project/final_projectmd.qmd
        text: "Portfolio Project"
  
format:
  html:
    theme: minty
    
editor: source