project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - Portfolio-project/final_projectqmd.qmd
  
website:
  title: "Erica Sherman's ePortfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: final_projectqmd.qmd
        text: "Portfolio Project"
        
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual
