project:
  type: website
  output-dir: docs
  
website:
  title: "Erica Sherman's ePortfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About Me"
        href: about.qmd
      - text: "Portfolio Project"
        href: Portfolio-project/final_projectqmd.qmd

format:
  html:
    theme: minty
    
editor: visual
